language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

env:
  - LUA="luajit 2.0.4"

before_install:
  - pip install hererocks
  - hererocks l -r^ --$LUA
  - export PATH=$PATH:$PWD/l/bin
  - luarocks install luafilesystem
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov-coveralls

install: true
  #- luarocks make # Uncomment if rockspec.

script:
  - luacheck src spec
  - busted -c

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
