language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

env:
  - LUA_VERSION="luajit 2.0.4" LUA_RUNTIME=luajit

before_install:
  - pip install hererocks
  - hererocks l -r^ --$LUA_VERSION
  - export PATH=$PATH:$PWD/l/bin
  - luarocks install luafilesystem
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov-coveralls

install: true
  #- luarocks make # Uncomment if rockspec.

before_script:
  - luacheck --formatter=TAP --codes --std=busted+$LUA_RUNTIME spec
  - luacheck --formatter=TAP --codes --std=$LUA_RUNTIME src

script:
  - busted -c

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
