language: python
sudo: false

env:
  - LUA=""
  - LUA="luajit"

before_install:
  - pip install hererocks
  - hererocks l -r^ --$LUA
  - export PATH=$PATH:$PWD/l/bin
  - luarocks install luacheck
  - luarocks install luafilesystem
  - luarocks install busted

install:
  - luarocks make

script:
  - luacheck src spec
  - busted -c

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
